In [ ]:
import os
import pickle


In [112]:
import pickle

# Load the object from the pickle file
X_dna_chars = pickle.load(open('./data/X_dna_chars.pkl', 'rb'))


In [113]:
headers_dna = pickle.load(open('./data/headers_dna.pkl', 'rb'))
X_protein_chars = pickle.load(open('./data/X_protein_chars.pkl', 'rb'))
headers_PROT = pickle.load(open('./data/headers_protein.pkl', 'rb'))    

In [114]:
headers_dna

[">AAA03550.1_aac(2')-Ia",
 '>AAA16241.1_ompR_ABFGGZ010000015.1',
 '>AAA16360.1_stxA2',
 '>AAA16527.1_ant(9)-Ib',
 '>AAA18472.1_ystA',
 '>AAA18786.1_cdtB',
 '>AAA19190.1_stxB2',
 '>AAA19777.1_seh',
 '>AAA19882.1_blaF',
 '>AAA19915.1_aac(3)-IId',
 '>AAA20116.1_tetA(P)',
 '>AAA20117.1_tetB(P)',
 '>AAA20192.1_erm(C)',
 '>AAA20885.1_astA',
 '>AAA21094.1_arsA',
 '>AAA21095.1_arsB_ABFGGZ010000001.1',
 '>AAA21096.1_arsC_ABFGGZ010000001.1',
 '>AAA21532.1_cepA',
 ">AAA21889.1_aac(6')-I",
 '>AAA22081.1_catB1',
 '>AAA22190.1_aadK',
 '>AAA22277.1_bmr',
 '>AAA22289.1_cat86',
 '>AAA22419.1_erm(G)',
 '>AAA22595.1_erm(D)',
 '>AAA22851.1_tet(L)',
 '>AAA22904.1_cfiA',
 '>AAA23018.1_catA13',
 '>AAA23033.2_tet(O)',
 '>AAA23215.1_catA16',
 '>AAA23235.1_etx',
 '>AAA23263.1_bont_F6',
 '>AAA23405.1_fasA',
 '>AAA23421.1_fim41a',
 '>AAA23523.1_bmaE',
 '>AAA23737.1_f17a',
 '>AAA24032.1_faeG',
 '>AAA24035.1_faeG',
 '>AAA24293.1_papG-II',
 '>AAA24300.1_ftsI_ABFGGZ010000004.1',
 '>AAA24632.1_stxA2',
 '>AAA24653.1_s

In [115]:
headers_PROT

[">AAA03550.1_aac(2')-Ia",
 '>AAA16241.1_ompR_ABFGGZ010000015.1',
 '>AAA16360.1_stxA2',
 '>AAA16527.1_ant(9)-Ib',
 '>AAA18472.1_ystA',
 '>AAA18786.1_cdtB',
 '>AAA19190.1_stxB2',
 '>AAA19777.1_seh',
 '>AAA19882.1_blaF',
 '>AAA19915.1_aac(3)-IId',
 '>AAA20116.1_tetA(P)',
 '>AAA20117.1_tetB(P)',
 '>AAA20192.1_erm(C)',
 '>AAA20885.1_astA',
 '>AAA21094.1_arsA',
 '>AAA21095.1_arsB_ABFGGZ010000001.1',
 '>AAA21096.1_arsC_ABFGGZ010000001.1',
 '>AAA21532.1_cepA',
 ">AAA21889.1_aac(6')-I",
 '>AAA22081.1_catB1',
 '>AAA22190.1_aadK',
 '>AAA22277.1_bmr',
 '>AAA22289.1_cat86',
 '>AAA22419.1_erm(G)',
 '>AAA22595.1_erm(D)',
 '>AAA22851.1_tet(L)',
 '>AAA22904.1_cfiA',
 '>AAA23018.1_catA13',
 '>AAA23033.2_tet(O)',
 '>AAA23215.1_catA16',
 '>AAA23235.1_etx',
 '>AAA23263.1_bont_F6',
 '>AAA23405.1_fasA',
 '>AAA23421.1_fim41a',
 '>AAA23523.1_bmaE',
 '>AAA23737.1_f17a',
 '>AAA24032.1_faeG',
 '>AAA24035.1_faeG',
 '>AAA24293.1_papG-II',
 '>AAA24300.1_ftsI_ABFGGZ010000004.1',
 '>AAA24632.1_stxA2',
 '>AAA24653.1_s

In [151]:
X_protein_chars[0]

['XXX',
 'MQENYKILVVDDDMRLRALLERYLTEQGFQVRSVANAEQMDRLLTRESFHLMVLDLMLPGEDGLSICRRLRSQSNPMPIIMVTAKGEEVDRIVGLEIGADDYIPKPFNPRELLARIRAVLRRQANELPGAPSQEEAVIAFGKFKLNLGTREMFREDEPMPLTSGEFAVLKALVSHPREPLSRDKLMNLARGREYSAMERSIDVQISRLRRMVEEDPAHPRYIQTVWGLGYVFVPDGSKA',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'MLLAGTIFILTLVLVIWQPRGLGIGWSAAFGAALALATGGIQVADIPVVWHIVWNATATFIAVIIISLLLDESGFFEWAALHVSRWGRGRGRLLFTWIILLGAAVAALFANDGAALILTPIVIAMLRALGFSKGTMLAFVMAAGFIADTASLPLVVSNLVNIVSADFFAIGFREYASVMVPVDLAAILTTLAMLHLFFRKDIPPAWDMALLKAPATAIKDPATFRTGWGVLLLLLAGFFVLEPLGIPVSAIAALGAGILFAVAKRGRVINTGKVLRGAPWQIVIFSLGMYLVVYGLRNAGLTDYLTTVLNMLAERGLWAATLGTGILSAFLSSIMNNMPSVLVGALSIDGSAATGTIKEAMIYANVIGCDLGPKITPIGSLATLLWLHVLAQKHITIGWGYYFRCGITM',
 'SITIYHNPDCGTSRNTLALIRNSGAEPTVIYYLETPPSGDELRQLLAAMGIPVRALLRKNVEPYDALGLAEDRFTDDQIIDFMLQHPILINRPIVTTPQGTRLCRPSEVVLEILTAPQKGAFVKEDGEPVIDAAGQRVK',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX'

In [150]:
X_dna_chars[0]

['XXX',
 'TGAAACGCGTGCGCTTTTCGCCGCGCAGCTCCTTTGCTCGCACACTGCTCCTGATCGTCACCTTGCTGTTCGTCAGCCTGGTGACGACCTATCTGGTGGTACTGAATTTCGCGATCCTGCCGAGTCTCCAGCAGTTTAATAAAGTGTTAGCCTACGAAGTGCGTATGCTGATGACCGACAAACTGCAGCTGGAGGATGGCACCCAGCTGGTGGTGCCCCCGGCGTTTCGTCGTGAAATTTATCGCGAGCTGGGGATTTCGCTCTATTCCAATGAAGCGGCGGAAGACGCAGGCCTGCGCT',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'ACCCTGCCGGTGCTGCTTGTGACGCTGGCCGCGCTGGCGCTGCGTCTCTCCTTCAACCAGCCATGAGAACGTACTATGAGCATCACCATTTACCATAACCCTGACTGCGGCACCTCGCGTAATACGCTGGCGCTGATCCGTAACAGCGGCGCCGAGCCCACCGTTATCTATTATCTGGAGACGCCGCCGTCGGGTGATGAGCTGCGCCAGCTGCTCGCCGCGATGGGGATCCCGGTGCGCGCGCTGCTGCGGAAAAACGTCGAACCCTACGACGCGCTGGGCCTGGCGGAAGACCGGTTT',
 'TAGCGCGCAGAATGGCGCCGGCTGTAGCAGCCGGCATGCCGTGTTAAACCTGCTGTATGGTAGGCTCTCCAGGTATGTAGCGCCTGGATTGCTGACAATATTCTCGCTTAGCGCTATTTCTCCACTATCCAGTCTGTTTCCCTTACTTTTCCTGCCGTTATACACCGCCTCTGCGCCGGTGGTTTATGTCTCTCGATAAATTATTAACTGTTTGTTTTTAATGGGTAAAATTTCGTTTTGTGCGTAATGATATAAAGTCAACGTCGTTTGCATTAT

In [118]:
filename="/mnt/raid1b/kdan_data/Paper/Data_Acquisition/Assemblies/assemblies.txt"
# Open the file and read the lines into a list
assemblies=[]
with open(filename, 'r') as file:
    assemblies = file.readlines()

# Remove newline characters from each line
assemblies = [line.strip() for line in assemblies]


In [119]:
len(assemblies)

18916

In [120]:
assemblies

['ERR1878169',
 'ERR1878177',
 'ERR1878179',
 'ERR1878171',
 'ERR1878168',
 'ERR1878180',
 'ERR1878167',
 'ERR1878174',
 'ERR1878178',
 'ERR1878172',
 'ERR1878175',
 'ERR1878176',
 'ERR1878173',
 'ERR1878170',
 'SRR5385440',
 'SRR5386599',
 'SRR5386683',
 'SRR5385669',
 'GCA_024580235.1',
 'SRR5387305',
 'SRR5386658',
 'SRR5385825',
 'SRR5386835',
 'GCF_900085435.1',
 'SRR5386265',
 'SRR5386844',
 'GCF_001701445.1',
 'SRR5385773',
 'GCF_900085405.1',
 'SRR12518045',
 'SRR5386567',
 'SRR5386506',
 'SRR5386950',
 'GCF_000822765.1',
 'GCA_900182115',
 'GCA_900180755',
 'SRR5386825',
 'GCA_900181885',
 'GCF_000822325.1',
 'SRR4017928',
 'GCF_900093025.1',
 'SRR5385749',
 'SRR5385819',
 'GCF_900085395.1',
 'GCA_900182165',
 'SRR5387023',
 'SRR5386208',
 'SRR5386711',
 'SRR5385680',
 'GCA_900180975',
 'SRR5386974',
 'SRR5387244',
 'GCA_900180915',
 'GCA_900181725',
 'GCF_900092685.1',
 'SRR5386792',
 'SRR5386298',
 'SRR5386772',
 'SRR5385993',
 'GCF_000822465.1',
 'SRR5386694',
 'SRR5385986'

In [121]:
file="dna"
kmer_size=3

In [122]:
X = pickle.load(open("/mnt/raid1b/kdan_data/Paper/Machine_Learning/build_dataset/data/X_" + file +"_chars.pkl", 'rb'))
headers=pickle.load(open("/mnt/raid1b/kdan_data/Paper/Machine_Learning/build_dataset/data/headers_" + file +".pkl", 'rb'))




### ERR1878177

In [123]:
print(len(X[1]))
print(len(X))

2580
18916


In [124]:
headers

[">AAA03550.1_aac(2')-Ia",
 '>AAA16241.1_ompR_ABFGGZ010000015.1',
 '>AAA16360.1_stxA2',
 '>AAA16527.1_ant(9)-Ib',
 '>AAA18472.1_ystA',
 '>AAA18786.1_cdtB',
 '>AAA19190.1_stxB2',
 '>AAA19777.1_seh',
 '>AAA19882.1_blaF',
 '>AAA19915.1_aac(3)-IId',
 '>AAA20116.1_tetA(P)',
 '>AAA20117.1_tetB(P)',
 '>AAA20192.1_erm(C)',
 '>AAA20885.1_astA',
 '>AAA21094.1_arsA',
 '>AAA21095.1_arsB_ABFGGZ010000001.1',
 '>AAA21096.1_arsC_ABFGGZ010000001.1',
 '>AAA21532.1_cepA',
 ">AAA21889.1_aac(6')-I",
 '>AAA22081.1_catB1',
 '>AAA22190.1_aadK',
 '>AAA22277.1_bmr',
 '>AAA22289.1_cat86',
 '>AAA22419.1_erm(G)',
 '>AAA22595.1_erm(D)',
 '>AAA22851.1_tet(L)',
 '>AAA22904.1_cfiA',
 '>AAA23018.1_catA13',
 '>AAA23033.2_tet(O)',
 '>AAA23215.1_catA16',
 '>AAA23235.1_etx',
 '>AAA23263.1_bont_F6',
 '>AAA23405.1_fasA',
 '>AAA23421.1_fim41a',
 '>AAA23523.1_bmaE',
 '>AAA23737.1_f17a',
 '>AAA24032.1_faeG',
 '>AAA24035.1_faeG',
 '>AAA24293.1_papG-II',
 '>AAA24300.1_ftsI_ABFGGZ010000004.1',
 '>AAA24632.1_stxA2',
 '>AAA24653.1_s

In [125]:
X[1]

['XXX',
 'TGAGGCGATTGCGCTTCTCGCCACGAAGTTCATTTGCCCGTACGTTATTGCTCATCGTCACCTTGCTGTTTGTCAGCCTGGTGACGACTTATCTGGTGGTGCTGAACTTCGCGATTTTGCCGAGCCTCCAGCAGTTTAATAAAGTCCTCGCGTACGAAGTGCGTATGTTGATGACCGACAAACTGCAACTGGAGGACGGCACGCAGTTGGTTGTGCCTCCCGCTTTCCGTCGGGAGATCTACCGTGAGCTGGGGATCTCTCTCTATTCCAACGAAGCCGCCGAAGAGGCCGGGCTGCGTT',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'TAGAGGCCGTCGACAATGATAATCTGGATCAACGGACCTTTCGGCGCCGGAAAGACGACTCTCGCTGAGCGGCTGCGCGATCGGCGTCCGAAATCGCTGATCTTTGACCCTGAGGAAATCGGGTTCGTGGTGAAAGAAACGGTCCCCATACCAGCGAGCGGAGACTATCAGGATCTCCCCTTGTGGAGGGGACTTACGATCGCTGCGGTCAGCGAGATTCGCAGGAATTACTCGCAGGACATCATCATCCCAATGACGCTCGTGCACCCGGACTATCTGACTGAGATACTCGACGGGTTA',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'XXX',
 'CGCTTACTCATCCATTGCCTGTCACGGAGCATGTCTCATTGTTAGATGTGGGCTATCTCACTCCAGCCAGAGCCACCAACTCAGGGCTGAACAGTAAAAAAACCGACGCGAAGTCGGTTTTTTTACGTCCTGATTCAGACCTCCTTTCAAATGAATGCCCAACGCTTAATTCACACCTACACCTTTCTCTACACTTACATATTCGTTAAACCATATGTGTTTTTGACTTGTCCGCTTTGGTTTGTAACGCTGGTGGCGCTGGCGCTACACCTCTCT

In [126]:

# find the characters in it and check if they are valid
chars = set()
for i in range(len(X)):
    for j in range(len(X[i])):
        for char in X[i][j]:
            chars.add(char)

print("Characters found in the data:", chars)


Characters found in the data: {'T', 'X', 'N', 'C', 'G', 'A'}


In [127]:
# switch data shape to match their respective part together
dif_feat = []

for i in range(len(X[0])):
    dif_feat.append([])
    for j in range(len(X)):
        dif_feat[i].append(X[j][i])

#Find the number of assemblies
num_assemblies=len(dif_feat[0])
del X

In [128]:
len(dif_feat[0])

18916

In [129]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pickle
from tqdm import tqdm

In [130]:
# create a vectorizer for the kmer
vectorizer = CountVectorizer(analyzer='char', ngram_range=(kmer_size, kmer_size))

print("Fitting Vectorizer")
# find kmers for each feature
kmer_prot = []
k_mers=[]

for i in tqdm(range(len(dif_feat))):
    kmer_prot.append(vectorizer.fit_transform(dif_feat[i]))
    k_mers.append(vectorizer.get_feature_names_out())

# check the distribution buckets of the kmers
kmer_sizes = [seq[i].shape[1] for seq in kmer_prot]


Fitting Vectorizer


100%|███████████████████████████████████████| 2580/2580 [04:41<00:00,  9.18it/s]


In [131]:
# convert the sparse matrix (of vectorizer) to a list
new_list = []
new_list_range=[]
for i in range(len(kmer_prot)):
    new_list.append(kmer_prot[i].toarray().astype(np.int16))
    new_list_range.append(len(kmer_prot[i].toarray()[0]))

del kmer_prot

# filter the list to remove the ones with shape 1 (sequence with only X)
#filtered_list = [elem for elem in new_list if elem.shape[1] != 1]
df = pd.DataFrame([new_list_range, k_mers], columns=headers)
# Filter columns where the value is different than 1
filtered_df = df.loc[:, df.iloc[0] != 1]
# Get the columns that are retained
filtered_columns = filtered_df.columns
# Use these columns to get elements from another list
filtered_list = [new_list[i] for i, col in enumerate(df.columns) if col in filtered_columns]


print(len(filtered_list))
print(len(headers))


1111
2580


In [132]:
filtered_list

[array([[4, 2, 4, ..., 2, 8, 0],
        [2, 4, 5, ..., 9, 6, 0],
        [2, 4, 5, ..., 8, 5, 0],
        ...,
        [2, 4, 5, ..., 8, 5, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [2, 4, 5, ..., 9, 6, 0]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1

In [133]:
print("Bringing data to original shape")
# bring data to original shape
before_csr_list = [[[] for _ in range(len(filtered_list))] for _ in range(num_assemblies)]
for i in range(len(filtered_list)):
    for j in range(num_assemblies):
        before_csr_list[j][i] = filtered_list[i][j]


# Initialize lists to collect data for the new DataFrame
indices = []
kmers = []
gene_names = []

# Process the DataFrame to extract k-mers and their gene names
index_counter = 0
for gene in filtered_df.columns:
    kmer_list = filtered_df[gene][1]
    for kmer in kmer_list:
        kmers.append(kmer)
        indices.append(index_counter)
        gene_names.append(gene)
        index_counter += 1

# Create the new DataFrame
new_df = pd.DataFrame({
    'Index': indices,
    'K-mer': kmers,
    'Gene': gene_names
})


# concatenate all the arrays together to avoid padding
result = []
print("Concatenating data ")

for entry in before_csr_list:
    concatenated_vector = np.concatenate(entry)
    result.append(concatenated_vector)

del concatenated_vector
del before_csr_list

final_array = np.array(result)

Bringing data to original shape
Concatenating data 


In [134]:
index = assemblies.index("SRR3996241") if "SRR3996241" in assemblies else -1
print(index)  # Outputs: 2

1989


In [135]:
assemblies[1]

'ERR1878177'

In [136]:
assemblies[1989]

'SRR3996241'

In [137]:
final_array

array([[4, 2, 4, ..., 0, 0, 1],
       [2, 4, 5, ..., 0, 0, 1],
       [2, 4, 5, ..., 0, 0, 1],
       ...,
       [2, 4, 5, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [2, 4, 5, ..., 0, 0, 1]], dtype=int16)

In [138]:
len(final_array)

18916

In [139]:
len(final_array[0])

76146

In [140]:
assemblies[1]

'ERR1878177'

In [145]:
final_array[1]

array([2, 4, 5, ..., 0, 0, 1], dtype=int16)

In [108]:
final_array[1][74308]

np.int16(0)

In [90]:
len(final_array[1989])

84160

In [80]:
new_df.shape

(84160, 3)

In [75]:
new_df.iloc[322,:]

Index                       322
K-mer                       aac
Gene     >AAA19915.1_aac(3)-IId
Name: 322, dtype: object

In [81]:
array=new_df["Gene"]

In [142]:
# Find indices where the substring is in an element
#indices_with_substring = [(i, element) for i, element in enumerate(array) if "KIA78998.1_blaCRP" in element]
indices_with_substring = [i for i, element in enumerate(array) if "AAA16241.1_ompR" in element]
print(indices_with_substring)
#print(indices_with_substring)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]


In [147]:
new_df.iloc[2, :]

Index                                     2
K-mer                                   aag
Gene     >AAA16241.1_ompR_ABFGGZ010000015.1
Name: 2, dtype: object